apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-declarativo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1"
          memory: "500Mi"
